# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

# CONDITIONS WHICH TRIGGER OR NOT THE JOBS
trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - "*"

pr:
- master

variables:
  projectName: 'NetMonkey'
  solution: 'NetMonkey.sln'

  SolutionDir: $(System.DefaultWorkingDirectory)
  NuGetFolderName: 'NuGetFolder'
  NuGetFolderLocation: $(System.DefaultWorkingDirectory)
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  PackageBuildPath: '$(System.DefaultWorkingDirectory)/$(projectName)/bin/Release/*'

stages:
- stage: Deploy
  jobs:

  - job: 'GenerateAndPushNuGetPackage'
    pool:
      vmImage: 'windows-2019'

    steps:
    - task: NuGetToolInstaller@1
      displayName: "Installation NuGet Configuration"

    - task: NuGetCommand@2
      displayName: 'Restore NuGet packages'
      inputs:
        restoreSolution: $(solution)
        configuration: $(buildConfiguration)

    - task: VSBuild@1
      displayName: 'Compilation Isogeo.NetMonkeySolution'
      inputs:
        solution: '$(solution)'
        vsVersion: latest
        msbuildArchitecture: x64
        msbuildArgs: '/p:PackageAsSingleFile=false /p:SkipInvalidConfigurations=true'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: NuGetCommand@2
      displayName: 'Generation NuGet packages'
      inputs:
        command: 'pack'
        configuration: $(buildConfiguration)
        packagesToPack: '**\*.csproj;!**\*.Tests.csproj'

    - powershell: cd $(NuGetFolderLocation); if ($?){new-item -Name $(NuGetFolderName) -ItemType directory}
      displayName: 'Create NuGet Folder'

    - powershell: cd $(NuGetFolderLocation)\$(NuGetFolderName); if ($?){echo "*.xml`r*.xsd`r*.csv`r*.dll`r*.pdb`r*.metadata`r*.p7s`r*.targets`r*.props`r*.json`r*.cache`r*.XML`r*.config`r.git`r*.nuget/`r.gitignore`r*.sln`r*.csproj`r*.cs`r*.yml`r*.bat`r*.proj`r*.md`r*.csproj`r*.txt`r*.nuspec`r*.snk`r*.resx`r" > .artifactignore}; if ($?){Get-Content .artifactignore} else{echo "error generation artifactignore file"; exit 1}
      displayName: 'add .artifactignore file'

    - powershell: |
        Copy-Item -Path $(PackageBuildPath) -Destination $(NuGetFolderLocation)/$(NuGetFolderName)/$(projectName)
      displayName: 'Copy NuGet Packages to NuGet folder'

    - task: PublishPipelineArtifact@1
      displayName: 'Generation NuGet artifacts'
      inputs:
        artifact: $(projectName)
        path: $(NuGetFolderLocation)/$(NuGetFolderName)

    - task: NuGetCommand@2
      displayName: Publish NuGet packages to www.nuget.org
      inputs:
        command: 'push'
        packagesToPush: $(NuGetFolderLocation)/$(NuGetFolderName)/**/*.nupkg
        nuGetFeedType: 'external'
        publishFeedCredentials: 'NugetOrg_asIsogeo'